### ISSUE TITLE
repository structure

### ISSUE THREAD

**Issue by mkruijt** [DoctorOden/JavaScript.Module2#2]
hi @DoctorOden ,

Can you please fix your repo structure?

the files you have in Week3/Step3SPA, should be directly under week 3.
(just like you did correctly with the other repo's 🎉 )

ke bye 🙋

**Comment by DoctorOden** [comment]
Hallo, can you tell me how to remove that map "Step3SPA" then ?

**Comment by mkruijt** [comment]
yep, it's not really convenient. but you will first have to remove the files before you can remove the folder. So after that you will have to upload your files again but in week3

**Comment by DoctorOden** [comment]
holy moly, ok i will do that today when i find a good way work via GitBash
with GitHub, i remove now my candy desktop app and have a nice challenge to
sync and organaze my local pc folder with GitHub repo's.

2017-10-09 15:14 GMT+02:00 Maartje Kruijt <notifications@github.com>:

**Comment by mkruijt** [comment]
Haha actually, cloning you repo locally and just moving the file and pushing the changes with git is easier than trying to do it here.... So that can also be a good practice!
